# first, install Cypress, then run all tests (in parallel tbd)
stages:
  - build
  - test
  - deploy

# to cache both npm modules and Cypress binary we use environment variables
# to point at the folders we can list as paths in "cache" job settings
variables:
  npm_config_cache: "$CI_PROJECT_DIR/node_modules"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

# cache using branch name
# https://gitlab.com/help/ci/caching/index.md
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - cache/Cypress
    - node_modules

# this job installs NPM dependencies and Cypress
install:
  image: cypress/base:10
  stage: build
  environment: Production
  only:
    - master
  script:
    - yarn install
    - npx cypress verify

# this job runs cypress without jobs, parallel, or not fully e2e
# https://www.cypress.io/blog/2018/09/05/run-end-to-end-tests-on-ci-faster/
code_quality:
  image: cypress/base:10
  stage: test
  environment: Production
  only:
    - master
  script:
    - yarn test
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 day

deploy:
  # latest node image contains yarn
  image: node:latest
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - yarn global add now
    - yarn b
    - now --token=$NOW_TOKEN
